version: '3.7'

services:
#  app:
#    build:
#      context: .
#      dockerfile: docker/deploy/Dockerfile
#    restart: unless-stopped
#    depends_on:
#      - mysql
#    ports:
#      - 3000:3000

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: unless-stopped
    container_name: javadockerDB
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: file
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
    ports:
      - 3306:3306